### ISSUE TITLE
Move existing integrations to use external integration / controller pattern

### ISSUE THREAD

**Issue by Kircheneer** [nautobot/nautobot-app-ssot#459]
### Proposed Functionality

CVP, DNAC and Infoblox are already or will be soon using the external integration and/or controller models from Nautobot 2.1/2.2 respectively. The other integrations should follow this pattern.

**Comment by jdrew82** [comment]
To be clear, we'll be updating the following integrations to use either ExternalIntegration or Controller objects:

ACI - Controller
CVP - Controller
D42 - ExternalIntegration
IPFabric - Controller
ServiceNow - ExternalIntegration

**Comment by jdrew82** [comment]
After some discussion we've decided to not update the Arista CloudVision integration as it already uses ExternalIntegration and trying to update to Controller would be too complicated at this time.

**Comment by jdrew82** [comment]
We've agreed to also not update the IPFabric integration to use the Controller due to how the current setup is using the instance credentials to pull snapshots in the Job form. Updating to be dynamically queried based upon the Controller will require some custom Javascript and possibly overriding the Job form which is out of scope at this time.

**Comment by jdrew82** [comment]
Integrations have been updated in next branch and will be included in 3.0 release.
